### ISSUE TITLE
Build workflow not stable

### ISSUE THREAD

**Issue by hellma314** [giggls/web20mash#1]
Hey, thanks for the software project. I am (re-)building my mashcontroller and for this, I would like to build the project from scratch. For this purpose, I have written a setup script. During execution I ran into a problem:

Checking out the web20mash git-project, installing all dependencies and calling "sudo make install" ends in Error 127:
```
$sudo make install
clig cmdline.cli
make: clig: No such file or directory.
make: *** [Makefile.36: cmdline.c] Error 127
```

I feel like, this error is not reproducable in a reliable way though it totally makes sense, as the package is missing. How can I reliably build the package? 

What else have I tried?

I receive the same error for `make CC=arm-linux-gnueabi-gcc`.

Calling `dpkg-buildpackage -b -aarmel` announces missing dependencies, such as libmicrohttpd-dev etc (which are installed though).

Thanks and best regards!

**Comment by hellma314** [comment]
Addendum: I also cannot find clig as package through apt or find any information in the debian package archives.

**Comment by giggls** [comment]
First of all this should not happen on a fresh clone as cmdline.c should always be newer than cmdline.cli. However I now removed autobuilding cmdline.c from the Makefile.

Regarding libmicrohttpd-dev I can not confirm this. The debian/control file does contain this dependency. Likely you did not install the corresponding armel packages.

**Comment by hellma314** [comment]
Worked in the first iteration for me, now. Thanks a lot!
